"""
export_weights_to_js.py
Reads the trained ONNX model and the original CSV dataset,
then writes a self-contained game/model_weights.js file containing:
  - MODEL_WEIGHTS  : all W and B matrices from the ONNX graph
  - FEATURE_MEANS  : per-feature mean  (for z-score standardization)
  - FEATURE_STDS   : per-feature std   (must mirror what C++ CSVReader applied)
  - ALG_TYPE       : 'regressor' (linear final layer) or 'classifier' (sigmoid)
"""

import sys, json, csv, os
import numpy as np

try:
    import onnx
    from onnx import numpy_helper
except ImportError:
    print("ERROR: 'onnx' package not found. Run: pip install onnx")
    sys.exit(1)

ONNX_PATH   = sys.argv[1] if len(sys.argv) > 1 else 'build/game_ai.onnx'
DATA_PATH   = sys.argv[2] if len(sys.argv) > 2 else 'data/game_ai.csv'
OUT_PATH    = 'game/model_weights.js'
FEAT_COLS   = ['rel_x', 'rel_y', 'bullet_near', 'bullet_rel_x', 'difficulty']

# ── 1. Load ONNX weights ─────────────────────────────────────────────────────
model   = onnx.load(ONNX_PATH)
weights = {}
for init in model.graph.initializer:
    arr = numpy_helper.to_array(init).tolist()
    weights[init.name] = arr
print(f"Loaded {len(weights)} tensors from {ONNX_PATH}: {list(weights.keys())}")

# ── 2. Compute standardisation parameters from training data ──────────────────
data = {col: [] for col in FEAT_COLS}
with open(DATA_PATH) as f:
    for row in csv.DictReader(f):
        for col in FEAT_COLS:
            data[col].append(float(row[col]))

means = {col: float(np.mean(data[col])) for col in FEAT_COLS}
stds  = {col: float(max(np.std(data[col]), 1e-8)) for col in FEAT_COLS}
print("Feature means:", {k: round(v, 4) for k, v in means.items()})
print("Feature stds: ", {k: round(v, 4) for k, v in stds.items()})

# ── 3. Write JS file ──────────────────────────────────────────────────────────
os.makedirs('game', exist_ok=True)
with open(OUT_PATH, 'w') as f:
    f.write("// ================================================================\n")
    f.write("// model_weights.js  —  Auto-generated by export_weights_to_js.py\n")
    f.write("// DO NOT EDIT MANUALLY. Re-generate with: make game-export\n")
    f.write("// ================================================================\n\n")
    f.write(f"const MODEL_WEIGHTS = {json.dumps(weights, indent=2)};\n\n")
    f.write(f"const FEATURE_MEANS = {json.dumps(means)};\n\n")
    f.write(f"const FEATURE_STDS  = {json.dumps(stds)};\n\n")
    f.write(f"const FEATURE_NAMES = {json.dumps(FEAT_COLS)};\n\n")
    f.write( "const ALG_TYPE = 'regressor'; // linear output, clamp [0,1] in game\n")

print(f"Written -> {OUT_PATH}")
